# Generated by Django 5.1 on 2024-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_code',
            field=models.CharField(default=2062037802576, max_length=20, unique=True),
        ),
    ]
