# Generated by Django 5.1 on 2024-09-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_id_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_code',
        ),
    ]
