# Generated by Django 5.1 on 2024-08-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='categorys',
        ),
    ]
