# Generated by Django 5.1 on 2024-08-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_category_article_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
