# Generated by Django 5.1 on 2024-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_updated_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(related_name='articles', to='blog.category'),
        ),
    ]
