# Generated by Django 5.1 on 2024-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
