# Generated by Django 5.1 on 2024-12-02 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_contactus_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactus',
            name='favorite_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
