# Generated by Django 5.1 on 2024-12-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contactus_birth_date_contactus_favorite_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Birth_date',
            new_name='birth_date',
        ),
    ]
