# Generated by Django 5.1 on 2024-12-02 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_birth_date_contactus_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='favorite_color',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
