# Generated by Django 5.1 on 2024-12-02 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_contactus_favorite_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
